language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_url: 'https://github.com/simo680/Claude_Monet.git'  # Эту переменную нужно предварительно настроить в настройках вашего репозитория на сайте Travis CI
  local_dir: dist  # Папка, содержащая скомпилированные файлы Vue.js приложения
  on:
    branch: main 
